SELECT BancoSangre.ID, 
       BancoSangre.PERSONA_ID, 
       BancoSangre.TIPO_DONACION_ID, 
       BancoSangre.CANTIDAD_EN_ML, 
       BancoSangre.FE_DONACION, 
       BancoSangre.FE_EXPIRACION
FROM  BANCO_SANGRE BancoSangre;

SELECT * FROM TIPO_SANGRE;
SELECT * FROM PERSONA;
SELECT * FROM TIPO_DONACION;
SELECT * FROM BANCO_SANGRE;

SELECT PE.NOMBRE,
       PE.APELLIDO,
       PE.DOCUMENTO,
       (TS.TP_ABO || TS.TP_RH) AS TIPOSANGRE,
       PE.FE_NAC
  FROM PERSONA PE,
       TIPO_SANGRE TS
 WHERE TS.ID=PE.TIPO_SANGRE_ID;

SELECT PE.NOMBRE,
       PE.APELLIDO,
       (TS.TP_ABO || TS.TP_RH) AS TIPOSANGRE,
       TD.NOMBRE AS DONACION,
       BS.FE_DONACION,
       BS.FE_EXPIRACION       
  FROM PERSONA PE,
       TIPO_SANGRE TS,
       TIPO_DONACION TD,
       BANCO_SANGRE BS
 WHERE     PE.ID=BS.PERSONA_ID
       AND TS.ID=PE.TIPO_SANGRE_ID
       AND TD.ID=BS.TIPO_DONACION_ID;